In [1]:
import pandas as pd
import numpy as np

In [2]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024.csv'

In [3]:
COLS_NOMBRES = [
    'indicativo',
    'nombre',
    'provincia',
]

COLS_INTS = [
    'altitud'
]

COLS_FLOATS = [
    'tmed',
    'prec',
    'tmin',
    'tmax',
    'velmedia',
    'sol',
    'presMax',
    'presMin',
    'hrMedia',
    'dir',
    'racha',
    'hrMax',
    'hrMin'
]

COLS_NUMS = COLS_INTS + COLS_FLOATS

COL_FECHA = 'fecha'
COLS_HORAS = [
    'horaPresMax',
    'horaPresMin',
    'horatmin',
    'horatmax',
    'horaracha',
    'horaHrMax',
    'horaHrMin'
]

In [4]:
# dtypes_dict = {nombre: str for nombre in COLS_NOMBRES} | {num: float for num in COLS_NUMS}
test_dict = {decimal: 'Float64' for decimal in COLS_FLOATS if decimal != 'prec'}
test_dict

{'tmed': 'Float64',
 'tmin': 'Float64',
 'tmax': 'Float64',
 'velmedia': 'Float64',
 'sol': 'Float64',
 'presMax': 'Float64',
 'presMin': 'Float64',
 'hrMedia': 'Float64',
 'dir': 'Float64',
 'racha': 'Float64',
 'hrMax': 'Float64',
 'hrMin': 'Float64'}

In [5]:
df = pd.read_csv(PATH_VAL_CLIM,
                 sep=';', decimal = ',',
                 dtype = {nombre: 'string' for nombre in COLS_NOMBRES} |
                         {entero: 'Int64' for entero in COLS_INTS} |
                         {otros: 'object' for otros in COLS_FLOATS + COLS_HORAS},
                         # {decimal: 'Float64' for decimal in COLS_FLOATS if decimal != 'prec'},
                 parse_dates = [COL_FECHA])

In [6]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,hrMedia,horatmin,horatmax,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,"19,8","0,0","16,0","23,5","6,7",...,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,"4,0","0,0","0,0","8,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,"-5,0","0,4","-7,0","-3,0","3,1",...,100.0,23:59,15:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,"4,3","2,6","2,0","6,6","0,0",...,90.0,23:59,01:00,99.0,"7,2",00:13,NaN,NaN,NaN,NaN
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,"5,5","0,0","0,6","10,4","1,7",...,72.0,01:00,14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7427566,2024-12-31,9562X,MORELLA,CASTELLON,990,"4,8","0,0","0,8","8,8","1,4",...,85.0,07:08,13:42,12.0,"5,0",16:50,97.0,23:50,63.0,14:00
7427567,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,"4,2","0,0","-4,9","13,4","0,0",...,81.0,06:50,14:50,22.0,"3,1",16:20,100.0,09:00,50.0,14:10
7427568,2024-12-31,3254Y,MORA,TOLEDO,717,"2,0","0,0","-3,1","7,1","1,1",...,94.0,08:13,11:18,20.0,"3,9",14:30,100.0,09:20,80.0,11:20
7427569,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,NaN,"0,0",NaN,NaN,NaN,...,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7427570,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,"4,1","0,0","-1,8","10,0","1,4",...,80.0,Varias,14:25,99.0,"6,1",Varias,97.0,09:00,62.0,15:50

In [7]:
df_prep = df.copy(deep = True)

In [8]:
COL_PREC = 'prec'
# df_prep.loc[df[COL_PREC] == 'Ip', COL_PREC] = 0
df_prep = df_prep[df_prep[COL_PREC] != 'Acum']
df_prep[COL_PREC] = df_prep[COL_PREC].replace('Ip', 0)

In [9]:
df_prep[COLS_FLOATS] = df_prep[COLS_FLOATS].replace(',', '.', regex=True).apply(pd.to_numeric, errors = 'raise')

In [10]:
df_prep.dtypes

fecha          datetime64[ns]
indicativo     string[python]
nombre         string[python]
provincia      string[python]
altitud                 Int64
tmed                  float64
prec                  float64
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia               float64
horatmin               object
horatmax               object
dir                   float64
racha                 float64
horaracha              object
hrMax                 float64
horaHrMax              object
hrMin                 float64
horaHrMin              object
dtype: object

In [ ]:
# PENDIENTE: LIMPIEZA Y CONVERSIÓN DE HORAS
# MIRAR DIR: 88 y 99