In [25]:
import pandas as pd
import numpy as np

In [8]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024.csv'

In [11]:
dtypes_dict = {
    #'fecha': str,
    'indicativo': str,
    'nombre': str,
    'provincia': str,
    'altitud': float,
    'tmed': float,
    'prec': float,
    'tmin': float,
    'tmax': float,
    'velmedia': float,
    'sol': float,
    'presMax': float,
    #'horaPresMax': str,
    'presMin': float,
    # 'horaPresMin': str,
    'hrMedia': float,
    # 'horatmin': str,
    # 'horatmax': str,
    'dir': float,
    'racha': float,
    # 'horaracha': str,
    'hrMax': float,
    # 'horaHrMax': str,
    'hrMin': float,
    # 'horaHrMin': str
}

In [12]:
COLS_NOMBRES = [
    'indicativo',
    'nombre',
    'provincia',
]

COLS_NUMS = [
    'altitud',
    'tmed',
    'prec',
    'tmin',
    'tmax',
    'velmedia',
    'sol',
    'presMax',
    'presMin',
    'hrMedia',
    'dir',
    'racha',
    'hrMax',
    'hrMin',
]

COL_FECHA = 'fecha'
COLS_HORAS = [
    'horaPresMax',
    'horaPresMin',
    'horatmin',
    'horatmax',
    'horaracha',
    'horaHrMax',
    'horaHrMin'
]

In [14]:
# dtypes_dict = {nombre: str for nombre in COLS_NOMBRES} | {num: float for num in COLS_NUMS}

In [17]:
df = pd.read_csv(PATH_VAL_CLIM,
                 sep=';', decimal = ',',
                 dtypes = {nombre: str for nombre in COLS_NOMBRES},
                 parse_dates = ['fecha'],
                 low_memory = False)

In [18]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,hrMedia,horatmin,horatmax,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,19.8,"0,0",16.0,23.5,6.7,...,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,4.0,"0,0",0.0,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,-5.0,"0,4",-7.0,-3.0,3.1,...,100.0,23:59,15:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,4.3,"2,6",2.0,6.6,0.0,...,90.0,23:59,01:00,99.0,7.2,00:13,NaN,NaN,NaN,NaN
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,5.5,"0,0",0.6,10.4,1.7,...,72.0,01:00,14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7427566,2024-12-31,9562X,MORELLA,CASTELLON,990,4.8,"0,0",0.8,8.8,1.4,...,85.0,07:08,13:42,12.0,5.0,16:50,97.0,23:50,63.0,14:00
7427567,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,4.2,"0,0",-4.9,13.4,0.0,...,81.0,06:50,14:50,22.0,3.1,16:20,100.0,09:00,50.0,14:10
7427568,2024-12-31,3254Y,MORA,TOLEDO,717,2.0,"0,0",-3.1,7.1,1.1,...,94.0,08:13,11:18,20.0,3.9,14:30,100.0,09:20,80.0,11:20
7427569,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,NaN,"0,0",NaN,NaN,NaN,...,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7427570,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,4.1,"0,0",-1.8,10.0,1.4,...,80.0,Varias,14:25,99.0,6.1,Varias,97.0,09:00,62.0,15:50

In [19]:
df.dtypes

fecha          datetime64[ns]
indicativo             object
nombre                 object
provincia              object
altitud                 int64
tmed                  float64
prec                   object
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia                object
horatmin               object
horatmax               object
dir                    object
racha                 float64
horaracha              object
hrMax                  object
horaHrMax              object
hrMin                  object
horaHrMin              object
dtype: object

In [30]:
cols_nums_mal = [col for col in COLS_NUMS if df.dtypes[col] == object]
print(cols_nums_mal)

['prec', 'hrMedia', 'dir', 'hrMax', 'hrMin']

In [31]:
# Enumeración de las columnas, sus tipos y sus posibles valores.
print('\nColumnas:')
for column in cols_nums_mal:
    values = df[column].unique()
    dtype = df.dtypes[column]
    print(column + ':', dtype, values)

# Valores nulos en cada columna.
# print('\nValores nulos:')
# print(df.isnull().sum())

Columnas:
prec: object ['0,0' '0,4' '2,6' ... '710,8' '215,2' '114,3']
hrMedia: object ['90.0' nan '100.0' '72.0' '85.0' '80.0' '84.0' '79.0' '68.0' '67.0'
 '87.0' '82.0' '83.0' '91.0' '93.0' '73.0' '92.0' '77.0' '96.0' '75.0'
 '56.0' '81.0' '94.0' '53.0' '64.0' '76.0' '88.0' '97.0' '61.0' '89.0'
 '95.0' '62.0' '52.0' '60.0' '55.0' '65.0' '78.0' '86.0' '74.0' '54.0'
 '98.0' '69.0' '66.0' '99.0' '70.0' '71.0' '48.0' '57.0' '58.0' '40.0'
 '42.0' '59.0' '51.0' '63.0' '44.0' '49.0' '50.0' '45.0' '32.0' '43.0'
 '46.0' '36.0' '41.0' '30.0' '47.0' '39.0' '28.0' '27.0' '35.0' '19.0'
 '37.0' '23.0' '25.0' '17.0' '38.0' '34.0' '18.0' '33.0' '24.0' '31.0'
 '26.0' '22.0' '20.0' '21.0' '29.0' '13.0' '14.0' '12.0' '15.0' '10.0'
 '16.0' '11.0' '5.0' '7.0' '8.0' '9.0' '3.0' '4.0' '6.0' '2.0' '1.0']
dir: object [nan '99.0' '18.0' '34.0' '23.0' '32.0' '36.0' '27.0' '9.0' '5.0' '11.0'
 '33.0' '20.0' '14.0' '13.0' '2.0' '0.0' '25.0' '29.0' '7.0' '31.0' '16.0'
 '35.0' '22.0' '30.0' '4.0' '17.0' '10.0' '24.0' '12.0' '28.0' '15.0'
 '6.0' '19.0' '26.0' '8.0' '3.0' '21.0' '1.0' '88.0' '-9.0']
hrMax: object [nan '91.0' '97.0' '99.0' '89.0' '94.0' '92.0' '95.0' '98.0' '85.0' '74.0'
 '83.0' '86.0' '87.0' '84.0' '88.0' '93.0' '96.0' '78.0' '72.0' '71.0'
 '79.0' '80.0' '90.0' '73.0' '67.0' '75.0' '82.0' '70.0' '62.0' '100.0'
 '65.0' '77.0' '81.0' '58.0' '69.0' '50.0' '59.0' '68.0' '66.0' '60.0'
 '57.0' '56.0' '64.0' '76.0' '63.0' '52.0' '55.0' '61.0' '53.0' '54.0'
 '51.0' '45.0' '46.0' '48.0' '47.0' '44.0' '34.0' '49.0' '36.0' '37.0'
 '39.0' '25.0' '42.0' '38.0' '40.0' '43.0' '41.0' '35.0' '19.0' '27.0'
 '26.0' '30.0' '33.0' '32.0' '23.0' '31.0' '29.0' '20.0' '28.0' '12.0'
 '15.0' '14.0' '16.0' '24.0' '22.0' '13.0' '21.0' '6.0' '18.0' '17.0'
 '11.0' '2.0' '1.0' '4.0' '10.0' '7.0' '8.0' '9.0' '3.0' '103.0' '108.0'
 '5.0' '111.0']
hrMin: object [nan '35.0' '32.0' '42.0' '31.0' '34.0' '27.0' '25.0' '47.0' '44.0' '26.0'
 '52.0' '48.0' '57.0' '23.0' '64.0' '62.0' '46.0' '22.0' '54.0' '68.0'
 '56.0' '59.0' '75.0' '66.0' '45.0' '38.0' '33.0' '53.0' '55.0' '67.0'
 '63.0' '40.0' '28.0' '49.0' '70.0' '60.0' '29.0' '50.0' '65.0' '72.0'
 '39.0' '30.0' '77.0' '41.0' '43.0' '61.0' '74.0' '78.0' '69.0' '71.0'
 '84.0' '58.0' '51.0' '89.0' '80.0' '98.0' '36.0' '73.0' '96.0' '95.0'
 '83.0' '82.0' '94.0' '93.0' '86.0' '87.0' '90.0' '97.0' '88.0' '99.0'
 '81.0' '85.0' '79.0' '92.0' '91.0' '76.0' '37.0' '24.0' '20.0' '21.0'
 '18.0' '17.0' '16.0' '19.0' '15.0' '14.0' '13.0' '12.0' '11.0' '10.0'
 '9.0' '100.0' '7.0' '8.0' '6.0' '5.0' '4.0' '3.0' '2.0' '1.0' '0.0']

Valores nulos:
fecha                0
indicativo           0
nombre               0
provincia            0
altitud              0
tmed            366597
prec            242855
tmin            362080
tmax            361810
velmedia       1778919
sol            5363577
presMax        4888000
horaPresMax    4888287
presMin        4890726
horaPresMin    4891264
hrMedia        1258860
horatmin        808231
horatmax        804738
dir            1996155
racha          1996226
horaracha      1999258
hrMax          2571111
horaHrMax      2575676
hrMin          2570709
horaHrMin      2575224
dtype: int64

In [41]:
COL_PREC = 'prec'
cols_nums_mal.remove(COL_PREC)

In [43]:
df_prep = df.copy(deep = True)

In [44]:
df_prep[cols_nums_mal] = df_prep[cols_nums_mal].apply(pd.to_numeric, errors = 'raise')

In [45]:
df_prep.dtypes

fecha          datetime64[ns]
indicativo             object
nombre                 object
provincia              object
altitud                 int64
tmed                  float64
prec                   object
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia               float64
horatmin               object
horatmax               object
dir                   float64
racha                 float64
horaracha              object
hrMax                 float64
horaHrMax              object
hrMin                 float64
horaHrMin              object
dtype: object

In [37]:
df_prep['prec'] = pd.to_numeric(df_prep['prec'], errors='raise')

ValueError: Unable to parse string "0,0" at position 0

In [48]:
df_prep[COL_PREC] = pd.to_numeric(df_prep[COL_PREC].str.replace(',', '.'), errors='raise')

ValueError: Unable to parse string "Ip" at position 36

In [39]:
df_prep.dtypes

fecha          datetime64[ns]
indicativo             object
nombre                 object
provincia              object
altitud                 int64
tmed                  float64
prec                   object
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia               float64
horatmin               object
horatmax               object
dir                   float64
racha                 float64
horaracha              object
hrMax                 float64
horaHrMax              object
hrMin                 float64
horaHrMin              object
dtype: object

In [47]:
df_prep[COL_PREC].unique()

array(['0,0', '0,4', '2,6', ..., '710,8', '215,2', '114,3'],
      shape=(1618,), dtype=object)